version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "127.0.0.1:8554:8554"
  camera-simulator0:
    image: vagheshpatel/camera-simulator:1.0.0
    container_name: camera-simulator0
    network_mode: "host"
    depends_on:
      - camera-simulator
  OvmsServer:
    image: vagheshpatel/ovms-server:1.0.0
    container_name: ovms-server0
    restart: always
    ports:
      - '9001:9001'
      - '9002:9002'
  OvmsClient0:
    image: vagheshpatel/ovms-client:1.0.0
    container_name: object-detection0
    network_mode: "host"
    environment:
      - CONTAINER_NAME="object-detection0"
      - INPUTSRC=rtsp://localhost:8554/camera_0
    depends_on:
      - OvmsServer
    volumes:
      - ./results:/tmp/results   
