#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $
version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "127.0.0.1:8554:8554"
  camera-simulator0:
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/coca-cola-4465029-3840-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_0
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  OvmsServer:
    image: openvino/model_server:2023.1-gpu
    container_name: ovms-server0
    restart: always
    ports:
      - '9001:9001'
      - '9002:9002'
    command: 
      - '--config_path'
      - '/models/config.json'
      - '--port'
      - '9001'              
      - '--rest_port'
      - '9002'
      - '--log_level'
      - 'INFO'
    volumes:
      - ./configs/opencv-ovms/models/2022:/models
    environment:
      - DEVICE=CPU update_config:dev
      - PLATFORM="core"
      - server_cl_cache_dir=/home/pipeline-server/.cl-cache   
  OvmsClient0:
    build: 
      dockerfile: Dockerfile
      context: configs/opencv-ovms/demos/
    image: python-demo:dev
    container_name: object-detection0
    network_mode: "host"
    entrypoint: /opencv-ovms/scripts/docker_compose_generic_entrypoint.sh
    environment:
      - CONTAINER_NAME="object-detection0"
      - GRPC_PORT=9001
      - INPUTSRC=rtsp://localhost:8554/camera_0
      - cid_count=0
      - DETECTION_MODEL_NAME=ssd_mobilenet_v1_coco
      - DETECTION_LABEL_FILE=coco_91cl_bkgr.txt
      - DETECTION_ARCHITECTURE_TYPE=ssd
      - DETECTION_OUTPUT_RESOLUTION=1280x720
      - DETECTION_THRESHOLD=0.50
      - RENDER_MODE=1 #RENDER_MODE=1 will work only after running xhost +local:docker
      - DISPLAY=$DISPLAY
      - ENTRYPOINT_SCRIPT=/opencv-ovms/demos/object_detection/python/entrypoint.sh
    depends_on:
      - OvmsServer
    volumes:
      - ./configs/opencv-ovms:/opencv-ovms
      - ./results:/tmp/results   
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
