
version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - 8554
  camera-simulator0:
    build:
      context: ./rtsp-simulator
      dockerfile: Dockerfile
    image: camera-simulator:1.0.0
    container_name: camera-simulator0
    environment:
      - RTSP_SERVER=camera-simulator
    depends_on:
      - camera-simulator
  OvmsServer:
    build:
      context: ./server
      dockerfile: Dockerfile  
    image: ovms-server:1.0.0
    container_name: ovms-server0
    restart: always
    ports:
      - 9001
      - 9002
  OvmsClient0:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ovms-client:1.0.0
    container_name: object-detection0
    environment:
      - CONTAINER_NAME="object-detection0"
      - INPUTSRC=rtsp://camera-simulator:8554/camera_0
      - GRPC_URL=OvmsServer
    depends_on:
      - OvmsServer
    volumes:
      - ./results:/tmp/results   
